// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMA.Persistence;

#nullable disable

namespace PMA.Persistence.Migrations
{
    [DbContext(typeof(PMADBContext))]
    [Migration("20260612093409_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMA.Domain.Entities.Allergy", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("Appointmentreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Appointmenttype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("endappointment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("startappointment")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PMA.Domain.Entities.CardiologyConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ECGFindings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ECGPerformed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EchoPerformed")
                        .HasColumnType("boolean");

                    b.Property<int?>("EjectionFraction")
                        .HasColumnType("integer");

                    b.Property<bool>("HypertensionRisk")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmokingRisk")
                        .HasColumnType("boolean");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("CardiologyConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("documentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("documentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ClinicalDocuments");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalImage", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DermatologyConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("DermatologyConsultationId");

                    b.ToTable("ClinicalImages");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalRecord", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("PracticeId");

                    b.ToTable("ClinicalRecords");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Consultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("BillingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClinicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsultationNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Doctorid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PracticePractitionerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresFollowUp")
                        .HasColumnType("boolean");

                    b.Property<int>("SpecialtyTypes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reasonforvisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClinicalRecordId");

                    b.HasIndex("PracticePractitionerId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.DentistryConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("GumCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("XRayCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("DentistryConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.DermatologyConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedAreas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("DermatologyConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("PMA.Domain.Entities.HouseHoldInvoiceCollection", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Invoiceid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientHouseholdid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Patientid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Practiceid")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("invoiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("patientid")
                        .HasColumnType("integer");

                    b.Property<int>("practiceid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Invoiceid");

                    b.HasIndex("PatientHouseholdid");

                    b.HasIndex("Patientid");

                    b.HasIndex("Practiceid");

                    b.ToTable("HouseHoldInvoiceCollection");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OutStandingAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientMedicalAidId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PMA.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLineItems");
                });

            modelBuilder.Entity("PMA.Domain.Entities.MedicalAid", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DependentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalAids");
                });

            modelBuilder.Entity("PMA.Domain.Entities.OncologyConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancerStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChemotherapyCycle")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TumorResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("OncologyConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalAidId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicalAidName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalAidNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Dateofbirth")
                        .HasColumnType("date");

                    b.Property<string>("Displayname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identitynumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MedicalAidId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Organisationid")
                        .HasColumnType("uuid");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("Organisationid");

                    b.HasIndex("PracticeId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PatientHousehold", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MedicalAidId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactSurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticeId");

                    b.ToTable("PatientHousehold");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PatientReferral", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Consultationid")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("phone")
                        .HasColumnType("integer");

                    b.Property<string>("practice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Consultationid");

                    b.ToTable("PatientReferral");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PediatricsConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DevelopmentalMilestones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric");

                    b.Property<bool>("VaccinationsUpToDate")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("PediatricsConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Practice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticeNumber")
                        .IsUnique();

                    b.ToTable("practices", (string)null);
                });

            modelBuilder.Entity("PMA.Domain.Entities.PracticePractitioner", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Isactive")
                        .HasColumnType("boolean");

                    b.Property<string>("PracticeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticeId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("PracticePractitioners");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Practitioner", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HPCSANumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Licenseexpirydate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Yearsofexperience")
                        .HasColumnType("integer");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PractitionerAvailability", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PracticePractitionerId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticePractitionerId");

                    b.ToTable("PractitionerAvailabilities");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("consultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("medicationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("consultationId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Procedure", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("tariffAmount")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PsychiatryConsultation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Affect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelfHarmRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speech")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SuicidalIdeation")
                        .HasColumnType("boolean");

                    b.Property<string>("TherapyNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("PsychiatryConsultations");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ToothChart", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DentistryConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToothNumber")
                        .HasColumnType("integer");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("DentistryConsultationId");

                    b.ToTable("ToothCharts");
                });

            modelBuilder.Entity("PMA.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accountstatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Displayname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Failedloginattempts")
                        .HasColumnType("integer");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isemailverified")
                        .HasColumnType("boolean");

                    b.Property<bool>("Isphonenumberverified")
                        .HasColumnType("boolean");

                    b.Property<bool>("Istwofactorenabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Lastlogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastotp")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Passwordchangedat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("text");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PMA.Domain.Entities.UserPractice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPractices");
                });

            modelBuilder.Entity("PMA.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Isactive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PracticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("PracticeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Vital", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("numeric");

                    b.Property<int?>("DiastolicBP")
                        .HasColumnType("integer");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer");

                    b.Property<int?>("SystolicBP")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.Property<Guid>("consultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deletedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("deleteddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("height")
                        .HasColumnType("numeric");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("modifiedby")
                        .HasColumnType("text");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("oxygenSaturation")
                        .HasColumnType("integer");

                    b.Property<int?>("respiratoryRate")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("consultationId")
                        .IsUnique();

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("PatientPatientHousehold", b =>
                {
                    b.Property<Guid>("Householdsid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Patientsid")
                        .HasColumnType("uuid");

                    b.HasKey("Householdsid", "Patientsid");

                    b.HasIndex("Patientsid");

                    b.ToTable("PatientPatientHousehold");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Allergy", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("PMA.Domain.Entities.PatientHousehold", "PatientHousehold")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PatientHousehold");

                    b.Navigation("Practice");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("PMA.Domain.Entities.CardiologyConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("CardiologyConsultation")
                        .HasForeignKey("PMA.Domain.Entities.CardiologyConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalDocument", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "DoctorConsultation")
                        .WithMany("Documents")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorConsultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalImage", b =>
                {
                    b.HasOne("PMA.Domain.Entities.DermatologyConsultation", "DermatologyConsultation")
                        .WithMany("ClinicalImages")
                        .HasForeignKey("DermatologyConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DermatologyConsultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalRecord", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Patient", "Patient")
                        .WithOne("ClinicalRecord")
                        .HasForeignKey("PMA.Domain.Entities.ClinicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Consultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("PMA.Domain.Entities.ClinicalRecord", "ClinicalRecord")
                        .WithMany("DoctorVisits")
                        .HasForeignKey("ClinicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.PracticePractitioner", "PracticePractitioner")
                        .WithMany()
                        .HasForeignKey("PracticePractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ClinicalRecord");

                    b.Navigation("PracticePractitioner");
                });

            modelBuilder.Entity("PMA.Domain.Entities.DentistryConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("DentistryConsultation")
                        .HasForeignKey("PMA.Domain.Entities.DentistryConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.DermatologyConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("DermatologyConsultation")
                        .HasForeignKey("PMA.Domain.Entities.DermatologyConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "DoctorConsultation")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorConsultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.HouseHoldInvoiceCollection", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("Invoiceid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.PatientHousehold", null)
                        .WithMany("HouseHoldInvoice")
                        .HasForeignKey("PatientHouseholdid");

                    b.HasOne("PMA.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("Practiceid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Patient");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("Invoice")
                        .HasForeignKey("PMA.Domain.Entities.Invoice", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.MedicalAid", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Patient", "Patient")
                        .WithMany("MedicalAids")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Domain.Entities.OncologyConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("OncologyConsultation")
                        .HasForeignKey("PMA.Domain.Entities.OncologyConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Patient", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Organisation", null)
                        .WithMany("Patients")
                        .HasForeignKey("Organisationid");

                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany("Patients")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PatientHousehold", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PatientReferral", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", null)
                        .WithMany("Refferals")
                        .HasForeignKey("Consultationid");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PediatricsConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("PediatricsConsultation")
                        .HasForeignKey("PMA.Domain.Entities.PediatricsConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PracticePractitioner", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany("PracticePractitioners")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Practitioner", "Practitioner")
                        .WithMany("PracticePractitioners")
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Practitioner", b =>
                {
                    b.HasOne("PMA.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PractitionerAvailability", b =>
                {
                    b.HasOne("PMA.Domain.Entities.PracticePractitioner", "PracticePractitioner")
                        .WithMany("Availabilities")
                        .HasForeignKey("PracticePractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticePractitioner");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "consultation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("consultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Procedure", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "DoctorConsultation")
                        .WithMany("Procedures")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorConsultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PsychiatryConsultation", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "Consultation")
                        .WithOne("PsychiatryConsultation")
                        .HasForeignKey("PMA.Domain.Entities.PsychiatryConsultation", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.ToothChart", b =>
                {
                    b.HasOne("PMA.Domain.Entities.DentistryConsultation", "DentistryConsultation")
                        .WithMany("ToothCharts")
                        .HasForeignKey("DentistryConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DentistryConsultation");
                });

            modelBuilder.Entity("PMA.Domain.Entities.UserPractice", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.User", "User")
                        .WithMany("UserPractices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PMA.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Practice", "Practice")
                        .WithMany()
                        .HasForeignKey("PracticeId");

                    b.HasOne("PMA.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Vital", b =>
                {
                    b.HasOne("PMA.Domain.Entities.Consultation", "consultation")
                        .WithOne("Vital")
                        .HasForeignKey("PMA.Domain.Entities.Vital", "consultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consultation");
                });

            modelBuilder.Entity("PatientPatientHousehold", b =>
                {
                    b.HasOne("PMA.Domain.Entities.PatientHousehold", null)
                        .WithMany()
                        .HasForeignKey("Householdsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("Patientsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PMA.Domain.Entities.ClinicalRecord", b =>
                {
                    b.Navigation("DoctorVisits");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Consultation", b =>
                {
                    b.Navigation("CardiologyConsultation")
                        .IsRequired();

                    b.Navigation("DentistryConsultation")
                        .IsRequired();

                    b.Navigation("DermatologyConsultation")
                        .IsRequired();

                    b.Navigation("Diagnoses");

                    b.Navigation("Documents");

                    b.Navigation("Invoice");

                    b.Navigation("OncologyConsultation")
                        .IsRequired();

                    b.Navigation("PediatricsConsultation")
                        .IsRequired();

                    b.Navigation("Prescriptions");

                    b.Navigation("Procedures");

                    b.Navigation("PsychiatryConsultation")
                        .IsRequired();

                    b.Navigation("Refferals");

                    b.Navigation("Vital")
                        .IsRequired();
                });

            modelBuilder.Entity("PMA.Domain.Entities.DentistryConsultation", b =>
                {
                    b.Navigation("ToothCharts");
                });

            modelBuilder.Entity("PMA.Domain.Entities.DermatologyConsultation", b =>
                {
                    b.Navigation("ClinicalImages");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Appointments");

                    b.Navigation("ClinicalRecord")
                        .IsRequired();

                    b.Navigation("MedicalAids");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PatientHousehold", b =>
                {
                    b.Navigation("HouseHoldInvoice");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Practice", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("PracticePractitioners");
                });

            modelBuilder.Entity("PMA.Domain.Entities.PracticePractitioner", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("PMA.Domain.Entities.Practitioner", b =>
                {
                    b.Navigation("PracticePractitioners");
                });

            modelBuilder.Entity("PMA.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPractices");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
